### ISSUE TITLE
When Source is abort'ed, persist checkpoint.

### ISSUE THREAD

**Issue by sroze** [equinox-project/equinox-js#49]
When consumers are shutdown, we expect the application to abort the signal sent to `source.start`. When this is the case, we should persist the last checkpoint.

**Comment by nordfjord** [comment]
This is already happening, see https://github.com/equinox-project/equinox-js/blob/3c7b839c0fa1f28c9836f0fc6fb764576fea44ab/packages/propeller/src/FeedSource.mts#L72-L76
