### ISSUE TITLE
docs: Getting started guide is broken

### ISSUE THREAD

**Issue by tburny** [equinox-project/equinox-js#63]
I would like to learn equinox-js and experiment a little with this nice project. However I am instantly hitting a wall, because copy-pasting the code from https://equinox-project.github.io/equinox-js/docs/intro leads to several errors.

First it does not mention which libraries I need to install in order to run this code.
Next 

In this line

```typescript
export class Service {
  constructor(private readonly resolve: (accountId: AccountId) => Decider<Event, State>) {}
```
the namespaces need to be added so that there are at least no obvious compile errors in VSCode:
```
export class Service {
  constructor(private readonly resolve: (accountId: AccountId) => Decider<Events.Event, Fold.State>) {}
```

Continuing to the testing snippet, I came up with the following code (adding namespaces):
```typescript
import { Events, Fold, Decide } from "./quick-start"
import { test, expect } from "vitest"

const given = (initial:Fold.State, events: Events.Event[], interpret: (state: Fold.State) => Event[]) =>
  interpret(Fold.fold(initial, events))

test("Depositing", () => {
  expect(given(0, [], Decide.deposit(100))).toEqual([{ type: "Deposited", data: { amount: 100 } }])
})

test("Withdrawing with no funds", () => {
  expect(() => given(0, [], Decide.withdraw(100))).toThrow("Insufficient funds")
})

test("Withdrawing with funds", () => {
  expect(given(0, [{ type: "Deposited", data: { amount: 100 } }], Decide.withdraw(50))).toEqual([
    {
      type: "Withdrawn",
      data: { amount: 50 },
    },
  ])
})

```

1. It seems that `given` lacks the `initial` state in the original source code
2. VSCode shows me an error for `Decide.deposit` / `Decide.withdraw`: `Argument of type '(state: State) => Event[]' is not assignable to parameter of type '(state: number) => Event[]'.ts(2345)`

Any help would be appreciated! Also is it possible to add the examples to the documentation in a way that they can actually be run and tested as part of the CI build?

**Comment by nordfjord** [comment]
Thanks for this, I've fixed a few of the inconsistencies in the docs as of #64. I'll see if there's a good way to get type checking in the docs project for the snippets, but am not hopeful as often one code snippet is followed by a paragraph explaining a better way, and then another code snippet. If I just dump the ts snippets into a file that causes unfortunate "duplicate identifier" issues and I quite like that style of docs. I have added a little checker tool that can be used with a human in the loop though.

Closing as fixed for now
